import React from "react"
import { InvestigationResult } from "../../types/investigation"
import { RuleScorecard } from "../hypothesis/RuleScorecard"
import { Scale, CheckCircle2, XCircle, AlertTriangle, ShieldCheck } from "lucide-react"

interface E6ChallengeWorkspaceProps {
  result: InvestigationResult
}

export const E6ChallengeWorkspace: React.FC<E6ChallengeWorkspaceProps> = ({ result }) => {
  const scored = result.scored || []
  const hypothesesMap = new Map((result.hypotheses || []).map((h) => [h.hypothesis_id, h]))

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Stage Header */}
      <header className="space-y-2 border-b border-[#2E2E2E] pb-4">
        <div className="flex items-center justify-between">
          <span className="px-2 py-0.5 rounded bg-[#6B9BB0]/20 text-[#F4EEE0] font-mono text-xs font-bold border border-[#6B9BB0]/40">
            STAGE E6 · RULE CHALLENGE
          </span>
          <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#1C1C1C] text-[#9E9788] border border-[#2E2E2E]">
            [RULES]
          </span>
        </div>
        <h1 className="text-2xl font-bold font-sans text-[#F4EEE0] tracking-tight">
          System Self-Challenge &amp; Constraint Auditing
        </h1>
        <p className="text-xs text-[#9E9788] font-sans leading-relaxed max-w-3xl">
          The system actively challenges candidate explanations against 5 deterministic rules (Timeline Precedence, Segment Alignment, KPI Corroboration, Mechanism Consistency, Contradiction Guard) to prevent hallucinations.
        </p>
      </header>

      {/* 5-Rule Challenge Cards per Hypothesis */}
      {scored.length === 0 ? (
        <div className="p-8 rounded-2xl bg-[#1C1C1C] border border-[#2E2E2E] space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-[#6B9BB0]/15 border border-[#6B9BB0]/30 flex items-center justify-center text-[#6B9BB0]">
              <Scale className="w-5 h-5" />
            </div>
            <div>
              <div className="text-sm font-bold font-mono text-[#F4EEE0] flex items-center gap-2">
                <span>RULE CHALLENGE INACTIVE</span>
                <span className="text-[10px] px-2 py-0.5 rounded bg-[#222222] text-[#9E9788] font-mono border border-[#333333] font-bold">
                  NO CANDIDATES TO AUDIT
                </span>
              </div>
              <div className="text-xs text-[#9E9788] font-mono mt-0.5">
                Engine E6 [RULES] · 5-Rule Deterministic Evaluation
              </div>
            </div>
          </div>

          <p className="text-xs text-[#D1C9B8] font-sans leading-relaxed">
            The 5 deterministic challenge rules (Timeline Precedence, Segment Alignment, KPI Corroboration, Mechanism Consistency, and Contradiction Guard) audit candidate explanations generated by Stage E5. Because hypothesis generation was suppressed for this scenario and persona, rule scoring was bypassed.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2 font-mono text-xs">
            <div className="p-3 rounded-xl bg-[#141414] border border-[#2E2E2E] space-y-1">
              <span className="text-[10px] text-[#9E9788] uppercase block">Candidate Hypotheses</span>
              <span className="font-bold text-[#F4EEE0]">0 evaluated</span>
            </div>
            <div className="p-3 rounded-xl bg-[#141414] border border-[#2E2E2E] space-y-1">
              <span className="text-[10px] text-[#9E9788] uppercase block">Engine Status</span>
              <span className="font-bold text-[#E56B62]">Abstention Active</span>
            </div>
          </div>
        </div>
      ) : (
        <div className="space-y-5">
          {scored.map((sh) => {
            const hypObj = hypothesesMap.get(sh.hypothesis_id)
            const isWinning = sh.final_score >= 0.70

            return (
              <div
                key={sh.hypothesis_id}
                className="p-6 rounded-2xl bg-[#1C1C1C] border border-[#2E2E2E] space-y-4"
              >
                {/* Hypothesis Header with Statement & Calibrated Score Bar */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-[#2E2E2E]">
                  <div className="flex items-start sm:items-center gap-3">
                    <span className={`text-xs font-mono font-bold px-2.5 py-1 rounded-lg border ${
                      isWinning
                        ? "bg-[#4E8569]/20 text-[#78AC91] border-[#4E8569]/40"
                        : "bg-[#181818] text-[#9E9788] border-[#333333]"
                    }`}>
                      {sh.hypothesis_id}
                    </span>
                    <div>
                      <h3 className="text-sm font-bold font-sans text-[#F4EEE0]">
                        {hypObj?.statement || `${sh.hypothesis_id} Candidate Hypothesis`}
                      </h3>
                      <p className="text-xs text-[#9E9788] font-sans mt-0.5">
                        {hypObj?.reasoning || "Self-challenge rule evaluation and contradiction penalty verification."}
                      </p>
                    </div>
                  </div>

                  {/* Score Pills */}
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono shrink-0">
                    <span className="px-2 py-0.5 rounded bg-[#222222] text-[#9E9788] border border-[#333333]">
                      Support: <strong className="text-[#4E8569]">{(sh.support_score * 100).toFixed(0)}%</strong>
                    </span>

                    {sh.contradiction_penalty > 0 && (
                      <span className="px-2 py-0.5 rounded bg-[#D8453A]/20 text-[#E56B62] border border-[#D8453A]/40 font-bold">
                        Penalty: -{(sh.contradiction_penalty * 100).toFixed(0)}%
                      </span>
                    )}

                    <span className={`px-2.5 py-0.5 rounded font-bold border ${
                      isWinning
                        ? "bg-[#4E8569]/25 text-[#F4EEE0] border-[#4E8569]/50"
                        : "bg-[#222222] text-[#9E9788] border-[#333333]"
                    }`}>
                      Final: {(sh.final_score * 100).toFixed(0)}%
                    </span>
                  </div>
                </div>

                {/* Render Option A: Structured 5-Rule Checklist Table */}
                <RuleScorecard ruleResults={sh.rule_results} />
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
