"""
engines/memory.py — Engine E9: Memory Engine [RETRIEVAL]+[LLM]

Stores investigation precedents and retrieves similar past investigations.
Each precedent is embedded as a text summary and stored in a ChromaDB collection
backed by bge-m3 embeddings (pre-computed via OllamaProvider.embed).

The LLM generates a concise natural-language summary; ChromaDB provides the
vector search.  Retrieved precedents are stamped with MethodTag.RETRIEVAL.

Requirements: 15.1, 15.2, 15.3, 15.4, 15.5
"""

from __future__ import annotations

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from models import (
    ConfidenceState,
    InvestigationResult,
    MethodTag,
    OutcomeType,
)
from llm.provider import LLMProvider, LLMUnavailableError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_COLLECTION_NAME = "investigation_precedents"
_RELEVANCE_THRESHOLD = 0.7   # minimum cosine-similarity score [0, 1]
_MAX_RESULTS = 10
_MAX_RETRY_ATTEMPTS = 3
_STORE_TIMEOUT_S = 60.0        # Requirement 15.1 — within 5 seconds
DEFAULT_CANDIDATE_MULTIPLIER = 5  # Candidate oversampling compensates for post-retrieval authorization/provenance filtering.

# Explicit retrieval weights for confidence states (ISSUE-002 Phase 1)
# Preserves the strict invariant: HIGH > MEDIUM > ABSTAIN > LOW for equivalent semantic relevance
RETRIEVAL_WEIGHTS: dict[ConfidenceState, float] = {
    ConfidenceState.HIGH: 1.0,
    ConfidenceState.MEDIUM: 0.6,
    ConfidenceState.ABSTAIN: 0.2,
    ConfidenceState.LOW: 0.1,
}

# Retrieval score boost for human-validated precedents (ISSUE-002 Phase 3)
# Applied additively after confidence weighting; ensures human-validated
# precedents rank above unvalidated ones when otherwise comparable.
HUMAN_VALIDATION_BOOST: float = 0.1


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _cosine_to_relevance(chroma_distance: float) -> float:
    """
    Convert a ChromaDB L2 / cosine distance to a [0, 1] relevance score.

    ChromaDB with cosine space returns distances in [0, 2] (0 = identical).
    We map: relevance = 1 - distance/2  →  identical = 1.0, opposite = 0.0.
    """
    return max(0.0, min(1.0, 1.0 - chroma_distance / 2.0))


def _build_fallback_summary(result: InvestigationResult) -> str:
    """
    Build a template summary when the LLM is unavailable or fails.
    Does NOT call the LLM — used as the last resort.
    """
    winning_id = None
    winning_action = None
    confidence = None

    if result.decision:
        winning_id = result.decision.winning_hypothesis_id
        winning_action = result.decision.recommended_action

    if result.scored:
        top = max(result.scored, key=lambda s: s.final_score)
        confidence = top.confidence_state.value

    parts = [f"Investigation {result.scenario_id} for persona {result.persona.value}."]
    if winning_id:
        parts.append(f"Winning hypothesis: {winning_id}.")
    if confidence:
        parts.append(f"Confidence: {confidence}.")
    if winning_action:
        # Keep it short — strip to 200 chars so the embedding stays focused
        action_snippet = winning_action[:200].rstrip()
        parts.append(f"Recommended action: {action_snippet}.")
    return " ".join(parts)


# ---------------------------------------------------------------------------
# MemoryEngine
# ---------------------------------------------------------------------------

@dataclass
class PendingPrecedent:
    """An investigation result waiting to be retried."""

    result: InvestigationResult
    attempts: int = 0
    last_error: str = ""


class MemoryEngine:
    """
    Stores and retrieves investigation precedents using ChromaDB + LLM
    summarization.

    Collection: "investigation_precedents"
    Each precedent is stored as an embedded text summary generated by the LLM
    (or a deterministic fallback when the LLM is unavailable).

    Relevance scoring: ChromaDB returns cosine distances; we convert to [0, 1],
    weight by original confidence state (HIGH=1.0, MEDIUM=0.6, ABSTAIN=0.2, LOW=0.1),
    and filter by RELEVANCE_THRESHOLD (0.7) before returning results.

    Requirements: 15.1–15.5; ISSUE-002 Phase 1 & 2
    """

    COLLECTION_NAME: str = _COLLECTION_NAME
    RELEVANCE_THRESHOLD: float = _RELEVANCE_THRESHOLD
    MAX_RESULTS: int = _MAX_RESULTS
    MAX_RETRY_ATTEMPTS: int = _MAX_RETRY_ATTEMPTS
    CANDIDATE_MULTIPLIER: int = DEFAULT_CANDIDATE_MULTIPLIER
    RETRIEVAL_WEIGHTS: dict[ConfidenceState, float] = RETRIEVAL_WEIGHTS

    def __init__(
        self,
        chroma_client: Any,
        llm_provider: LLMProvider,
        candidate_multiplier: int | None = None,
    ) -> None:
        """
        Parameters
        ----------
        chroma_client : A chromadb.Client (or compatible) instance.
                        May be None for unit tests that don't exercise storage.
        llm_provider  : An LLMProvider for generating text summaries.
        candidate_multiplier : Factor by which MAX_RESULTS is multiplied for initial candidate retrieval.
        """
        self._chroma = chroma_client
        self._llm = llm_provider
        self._candidate_multiplier = (
            candidate_multiplier
            if candidate_multiplier is not None
            else self.CANDIDATE_MULTIPLIER
        )
        # Pending queue for failed store attempts (Req 15.2)
        self._pending: deque[PendingPrecedent] = deque()

    # ------------------------------------------------------------------
    # Collection accessor
    # ------------------------------------------------------------------

    def _get_or_create_collection(self) -> Any:
        """Return (creating if necessary) the ChromaDB collection."""
        if self._chroma is None:
            raise RuntimeError("chroma_client is not configured.")
        return self._chroma.get_or_create_collection(
            name=self.COLLECTION_NAME,
            metadata={"hnsw:space": "cosine"},
        )

    # ------------------------------------------------------------------
    # LLM summary generation
    # ------------------------------------------------------------------

    def summarize_investigation(self, result: InvestigationResult) -> str:
        """
        Use the LLM to generate a concise 2-3 sentence summary of the
        investigation for embedding.

        Falls back to a deterministic template summary if the LLM is
        unavailable or returns an empty response.

        Returns plain-text suitable for semantic search.
        """
        winning_id = (
            result.decision.winning_hypothesis_id
            if result.decision
            else None
        )
        recommended_action = (
            result.decision.recommended_action
            if result.decision
            else None
        )
        if result.decision and result.decision.abstained:
            confidence = ConfidenceState.ABSTAIN.value
        elif result.scored:
            top = max(result.scored, key=lambda s: s.final_score)
            confidence = top.confidence_state.value
        else:
            confidence = ConfidenceState.ABSTAIN.value

        system_prompt = (
            "You are a concise business intelligence analyst. "
            "Summarize investigations in 2-3 plain-English sentences. "
            "Do not include any numeric figures or confidence scores. "
            "Focus on: scenario, the winning hypothesis, and the recommended action."
        )
        user_prompt = (
            f"Summarize this investigation:\n"
            f"  scenario_id: {result.scenario_id}\n"
            f"  persona: {result.persona.value}\n"
            f"  winning_hypothesis: {winning_id or 'none'}\n"
            f"  confidence_state: {confidence or 'unknown'}\n"
            f"  recommended_action: {recommended_action or 'none (abstained)'}\n\n"
            "Write 2-3 sentences suitable for semantic search indexing."
        )

        try:
            response = self._llm.complete(
                user_prompt,
                model=getattr(self._llm, "DEFAULT_MODEL", "qwen3:8b"),
                system=system_prompt,
                temperature=0.0,
                max_tokens=200,
            )
            summary = response.text.strip()
            if summary:
                return summary
            logger.warning(
                "summarize_investigation: LLM returned empty text; "
                "using fallback summary for scenario=%s.",
                result.scenario_id,
            )
        except (LLMUnavailableError, Exception) as exc:
            logger.warning(
                "summarize_investigation: LLM call failed (%s); "
                "using fallback summary for scenario=%s.",
                exc,
                result.scenario_id,
            )

        return _build_fallback_summary(result)

    # ------------------------------------------------------------------
    # store_precedent
    # ------------------------------------------------------------------

    def store_precedent(
        self,
        result: InvestigationResult,
        outcome_type: OutcomeType = OutcomeType.OBSERVED,
    ) -> bool:
        """
        Store an investigation result as a searchable precedent.

        Stores valid investigation outcomes across all confidence states
        (HIGH, MEDIUM, LOW, ABSTAIN).

        Generates an LLM summary (or template fallback), embeds it with
        bge-m3 via the LLM provider, and upserts into the ChromaDB collection.

        Must complete within 5 seconds (Req 15.1).
        On failure, retains the result in a pending queue for retry up to
        MAX_RETRY_ATTEMPTS (3) before returning False (Req 15.2).

        Returns True on success, False when all retry attempts are exhausted.
        """
        return self._attempt_store(result, is_retry=False, outcome_type=outcome_type)

    def _attempt_store(
        self,
        result: InvestigationResult,
        *,
        is_retry: bool,
        pending: Optional[PendingPrecedent] = None,
        outcome_type: OutcomeType = OutcomeType.OBSERVED,
    ) -> bool:
        """
        Internal: attempt a single store operation with the 5-second deadline.
        Queues a PendingPrecedent on failure; returns True on success.
        """
        t_start = time.monotonic()
        scenario_id = result.scenario_id

        try:
            # 1. Build summary (LLM or fallback)
            summary = self.summarize_investigation(result)

            self._check_deadline(t_start, scenario_id)

            # 2. Build embedding via bge-m3
            embeddings = self._llm.embed([summary], model="bge-m3")
            vector: list[float] = embeddings[0]

            self._check_deadline(t_start, scenario_id)

            # 3. Build metadata
            winning_id = (
                result.decision.winning_hypothesis_id
                if result.decision
                else None
            )
            recommended_action = (
                result.decision.recommended_action
                if result.decision
                else None
            )
            if result.decision and result.decision.abstained:
                confidence_state_val = ConfidenceState.ABSTAIN.value
            elif result.scored:
                top = max(result.scored, key=lambda s: s.final_score)
                confidence_state_val = top.confidence_state.value
            else:
                confidence_state_val = ConfidenceState.ABSTAIN.value

            ot_val = outcome_type.value if hasattr(outcome_type, "value") else str(outcome_type)
            iso_now = datetime.now(tz=timezone.utc).isoformat()
            evidence_ids_str = ",".join(e.evidence_id for e in result.evidence) if result.evidence else ""
            source_ids_set = {
                e.source_id.strip()
                for e in (result.evidence or [])
                if getattr(e, "source_id", None) and str(e.source_id).strip()
            }
            source_ids_str = ",".join(sorted(source_ids_set))

            metadata = {
                "scenario_id": scenario_id,
                "persona": result.persona.value if hasattr(result.persona, "value") else str(result.persona),
                "source_ids": source_ids_str,
                "winning_hypothesis": winning_id or "",
                "recommendation": (recommended_action or "")[:500],
                "confidence_state": confidence_state_val,
                "original_confidence_state": confidence_state_val,
                "outcome_type": ot_val,
                "created_at": iso_now,
                "timestamp": iso_now,
                "evidence_ids": evidence_ids_str,
                "summary": summary[:1000],  # stored for retrieval result
                # ISSUE-002 Phase 3 — Human validation provenance
                "human_validated": False,
                "validated_at": "",
            }

            # 4. Upsert into ChromaDB
            collection = self._get_or_create_collection()

            # Preserve authoritative Analyst precedent records against restricted persona overwrites
            result_persona_str = result.persona.value if hasattr(result.persona, "value") else str(result.persona)
            try:
                existing = collection.get(ids=[scenario_id], include=["metadatas"])
                if existing and existing.get("metadatas") and len(existing["metadatas"]) > 0:
                    ex_meta = existing["metadatas"][0] or {}
                    if ex_meta.get("persona") == "analyst" and result_persona_str != "analyst":
                        logger.info(
                            "store_precedent: preserving authoritative analyst precedent for %s; skipping overwrite by %s run",
                            scenario_id, result_persona_str,
                        )
                        return True
            except Exception:
                pass

            collection.upsert(
                ids=[scenario_id],
                embeddings=[vector],
                documents=[summary],
                metadatas=[metadata],
            )

            self._check_deadline(t_start, scenario_id)

            logger.info(
                "store_precedent: stored scenario=%s confidence=%s outcome=%s (%.0f ms).",
                scenario_id,
                confidence_state_val,
                ot_val,
                (time.monotonic() - t_start) * 1000,
            )
            return True

        except _DeadlineExceeded as exc:
            error_msg = str(exc)
            logger.error(
                "store_precedent: deadline exceeded for scenario=%s: %s",
                scenario_id,
                error_msg,
            )
        except Exception as exc:  # noqa: BLE001
            error_msg = str(exc)
            logger.error(
                "store_precedent: failed for scenario=%s: %s",
                scenario_id,
                error_msg,
            )

        # ----------------------------------------------------------------
        # Failure path — enqueue for retry or increment attempt count
        # ----------------------------------------------------------------
        if pending is None:
            # First failure — create a new pending entry
            pending = PendingPrecedent(result=result, attempts=1, last_error=error_msg)
        else:
            pending.attempts += 1
            pending.last_error = error_msg

        if pending.attempts < self.MAX_RETRY_ATTEMPTS:
            logger.warning(
                "store_precedent: queuing retry %d/%d for scenario=%s.",
                pending.attempts,
                self.MAX_RETRY_ATTEMPTS,
                scenario_id,
            )
            self._pending.append(pending)
        else:
            logger.error(
                "store_precedent: all %d retry attempts exhausted for scenario=%s. "
                "Last error: %s",
                self.MAX_RETRY_ATTEMPTS,
                scenario_id,
                pending.last_error,
            )

        return False

    @staticmethod
    def _check_deadline(t_start: float, scenario_id: str) -> None:
        """Raise _DeadlineExceeded if the 5-second budget has been exceeded."""
        elapsed = time.monotonic() - t_start
        if elapsed > _STORE_TIMEOUT_S:
            raise _DeadlineExceeded(
                f"store_precedent exceeded {_STORE_TIMEOUT_S}s deadline for "
                f"scenario={scenario_id!r} (elapsed={elapsed:.2f}s)."
            )

    # ------------------------------------------------------------------
    # flush_pending — retry queued failures
    # ------------------------------------------------------------------

    def flush_pending(self) -> dict[str, int]:
        """
        Attempt to store all queued pending precedents.

        Returns a summary dict: {"succeeded": N, "failed": M}.
        Intended to be called by the orchestrator (or a background job)
        after the main pipeline completes.
        """
        succeeded = 0
        failed = 0
        while self._pending:
            pending = self._pending.popleft()
            ok = self._attempt_store(
                pending.result, is_retry=True, pending=pending
            )
            if ok:
                succeeded += 1
            else:
                failed += 1
        return {"succeeded": succeeded, "failed": failed}

    # ------------------------------------------------------------------
    # mark_validated — ISSUE-002 Phase 3
    # ------------------------------------------------------------------

    def mark_validated(
        self,
        scenario_id: str,
        validated_at: Optional[datetime] = None,
        validation_feedback_id: Optional[int] = None,
    ) -> bool:
        """
        Mark an existing precedent as human-validated.

        Updates the ChromaDB record's metadata to set human_validated=True,
        validated_at to the given (or current UTC) ISO timestamp, and
        optionally links the validation to the originating feedback_id.

        Does NOT alter confidence_state or original_confidence_state.

        Returns True on success, False if the record is not found or update fails.
        """
        try:
            collection = self._get_or_create_collection()
            # Retrieve existing record
            existing = collection.get(ids=[scenario_id], include=["metadatas"])
            if not existing or not existing.get("ids") or len(existing["ids"]) == 0:
                logger.warning(
                    "mark_validated: no precedent found for scenario=%s.",
                    scenario_id,
                )
                return False

            meta = (existing.get("metadatas") or [{}])[0] or {}
            ts = (validated_at or datetime.now(tz=timezone.utc)).isoformat()
            meta["human_validated"] = True
            meta["validated_at"] = ts
            if validation_feedback_id is not None:
                meta["validation_feedback_id"] = validation_feedback_id

            collection.update(
                ids=[scenario_id],
                metadatas=[meta],
            )
            logger.info(
                "mark_validated: scenario=%s marked as human-validated at %s (feedback_id=%s).",
                scenario_id,
                ts,
                validation_feedback_id,
            )
            return True

        except Exception as exc:  # noqa: BLE001
            logger.error(
                "mark_validated: failed for scenario=%s: %s",
                scenario_id,
                exc,
            )
            return False

    # ------------------------------------------------------------------
    # retrieve_precedents
    # ------------------------------------------------------------------

    def retrieve_precedents(
        self,
        scenario_id: str,
        query_context: str = "",
        include_simulated: bool = False,
        retention_config: Optional[dict] = None,
        authorized_sources: Optional[frozenset[str] | set[str] | list[str]] = None,
        persona: Optional[str] = None,
        region: Optional[str] = None,
        candidate_multiplier: Optional[int] = None,
    ) -> list[dict]:
        """
        Retrieve up to MAX_RESULTS precedents with relevance ≥ RELEVANCE_THRESHOLD,
        strictly bounded by persona authorized_sources entitlement (Req 15.3, 5.2).

        The query text is the scenario_id optionally enriched with free-form
        context (e.g. a short description of the KPI movement).

        Stamps each returned precedent with MethodTag.RETRIEVAL (Req 15.5).
        Incorporates confidence weighting (HIGH=1.0, MEDIUM=0.6, ABSTAIN=0.2, LOW=0.1)
        while preserving semantic similarity scoring.

        Returns
        -------
        A list of precedent dicts sorted by retrieval_score descending, each with:
            scenario_id       : str
            summary           : str
            relevance         : float  in [0, 1]
            confidence_state  : str
            original_confidence_state : str
            retrieval_weight  : float
            retrieval_score   : float
            outcome_type      : str ("observed" or "simulated")
            winning_hypothesis: str
            recommendation    : str
            timestamp         : str (ISO-8601)
            created_at        : str (ISO-8601)
            evidence_ids      : str
            source_ids        : list[str]
            human_validated   : bool
            validated_at      : str (ISO-8601 or empty)
            method            : MethodTag.RETRIEVAL

        Returns an empty list with an indication log when no relevant
        precedents are found (Req 15.4).

        Requirements: 15.3, 15.4, 15.5
        """
        query_text = query_context.strip() if query_context.strip() else scenario_id

        try:
            # Embed the query
            embeddings = self._llm.embed([query_text], model="bge-m3")
            query_vector: list[float] = embeddings[0]

            collection = self._get_or_create_collection()

            # Guard: if the collection is empty, return early
            count = collection.count()
            if count == 0:
                logger.info(
                    "retrieve_precedents: collection is empty for scenario=%s.",
                    scenario_id,
                )
                return []

            desired_results = self.MAX_RESULTS
            multiplier = candidate_multiplier if candidate_multiplier is not None else self._candidate_multiplier
            # Candidate oversampling compensates for post-retrieval authorization/provenance filtering.
            candidate_results = min(desired_results * max(1, multiplier), count)

            # ARCHITECTURAL DECISION (Round 2 E9 Scalability Optimization):
            # -------------------------------------------------------------
            # 1. ChromaDB local SQLite metadata filtering (where={"outcome_type": "observed"})
            #    was benchmarked as a severe bottleneck causing full-table scans & SQLite lock contention (9.4s+).
            # 2. Raw HNSW vector search is used strictly for candidate generation (sub-30ms at 100k scale).
            # 3. Python is the authoritative provenance, security, and authorization boundary (<1ms).
            # 4. Oversampling (candidate_multiplier=5 by default) is necessary because simulated or unauthorized
            #    precedents can occupy raw vector top-K slots before post-retrieval filtering drops them.
            # 5. The multiplier (5x) is benchmark-derived from controlled fixtures (yielding 100% recall) and must
            #    be periodically revalidated when corpus size or simulation distribution shifts materially.
            query_result = collection.query(
                query_embeddings=[query_vector],
                n_results=candidate_results,
                include=["documents", "metadatas", "distances"],
            )

        except Exception as exc:  # noqa: BLE001
            logger.error(
                "retrieve_precedents: ChromaDB query failed for scenario=%s: %s",
                scenario_id,
                exc,
            )
            return []

        # ----------------------------------------------------------------
        # Build result list, filtering by authorization, relevance, & confidence weighting
        # ----------------------------------------------------------------
        precedents: list[dict] = []
        auth_sources_set = frozenset(authorized_sources) if authorized_sources is not None else None

        ids_list: list[str] = (query_result.get("ids") or [[]])[0]
        distances_list: list[float] = (query_result.get("distances") or [[]])[0]
        metadatas_list: list[dict] = (query_result.get("metadatas") or [[]])[0]
        documents_list: list[str] = (query_result.get("documents") or [[]])[0]

        for doc_id, distance, meta, document in zip(
            ids_list, distances_list, metadatas_list, documents_list
        ):
            meta = meta or {}
            outcome_type_val = meta.get("outcome_type", "unknown")

            # Legacy / unknown provenance and simulated outcome protection:
            # Normal precedent retrieval strictly requires verified OBSERVED provenance.
            if not include_simulated and outcome_type_val != OutcomeType.OBSERVED.value:
                continue

            # ----------------------------------------------------------------
            # 1. Provenance Authorization Filtering (Security Engine Entitlement Invariant)
            # ----------------------------------------------------------------
            raw_sources = meta.get("source_ids", "")
            if raw_sources:
                candidate_sources = {s.strip() for s in raw_sources.split(",") if s.strip()}
            else:
                candidate_sources = set()

            if auth_sources_set is not None:
                # Fail-closed: If precedent lacks verified source_ids, it cannot be
                # proven to satisfy the active authorization boundary and MUST be excluded.
                if not candidate_sources:
                    logger.info(
                        "retrieve_precedents: failing closed on precedent %s due to missing/unverifiable source_ids under active authorization",
                        doc_id,
                    )
                    continue
                if not candidate_sources.issubset(auth_sources_set):
                    logger.info(
                        "retrieve_precedents: filtering unauthorized precedent %s (candidate_sources=%s not subset of authorized_sources=%s)",
                        doc_id, candidate_sources, auth_sources_set
                    )
                    continue

            # Region-scoped provenance filtering
            if region:
                prec_region = str(meta.get("region", "")).strip().lower()
                req_region = str(region).strip().lower()
                if prec_region and prec_region not in ("all", "global", req_region):
                    logger.info(
                        "retrieve_precedents: filtering regional precedent %s (prec_region=%s != req_region=%s)",
                        doc_id, prec_region, req_region
                    )
                    continue

            # ----------------------------------------------------------------
            # 2. Relevance Threshold Filtering
            # ----------------------------------------------------------------
            relevance = _cosine_to_relevance(distance)
            if relevance < self.RELEVANCE_THRESHOLD:
                continue

            # ----------------------------------------------------------------
            # 3. Domain-Specific Expiry Filtering (TTL)
            # ----------------------------------------------------------------
            if retention_config is not None:
                created_at_str = meta.get("created_at", "")
                if created_at_str:
                    try:
                        created_dt = datetime.fromisoformat(created_at_str)
                        if created_dt.tzinfo is None:
                            created_dt = created_dt.replace(tzinfo=timezone.utc)
                        # Look up TTL: try source_id from metadata, fall back to default
                        source_id = meta.get("source_id", "")
                        by_source = retention_config.get("by_source", {})
                        ttl_days = by_source.get(source_id, retention_config.get("default_ttl_days", 90))
                        expiry_dt = created_dt + timedelta(days=ttl_days)
                        if datetime.now(tz=timezone.utc) > expiry_dt:
                            logger.debug(
                                "retrieve_precedents: filtering expired precedent %s "
                                "(created=%s, ttl=%d days).",
                                doc_id, created_at_str, ttl_days,
                            )
                            continue
                    except (ValueError, TypeError):
                        # Malformed created_at — treat as expired (safe default)
                        logger.warning(
                            "retrieve_precedents: malformed created_at for %s; "
                            "filtering as expired.",
                            doc_id,
                        )
                        continue
                else:
                    # No created_at at all — treat as expired (safe default)
                    logger.warning(
                        "retrieve_precedents: missing created_at for %s; "
                        "filtering as expired.",
                        doc_id,
                    )
                    continue

            # ----------------------------------------------------------------
            # 4. Confidence Weighting
            # ----------------------------------------------------------------
            conf_state_str = meta.get("confidence_state") or meta.get("original_confidence_state") or ""
            try:
                conf_state = ConfidenceState(conf_state_str.lower()) if conf_state_str else None
                conf_weight = self.RETRIEVAL_WEIGHTS.get(conf_state, 0.1) if conf_state else 0.1
            except (ValueError, KeyError, AttributeError):
                conf_weight = 0.1
                conf_state = None

            retrieval_score = round(relevance * conf_weight, 4)

            # ----------------------------------------------------------------
            # 5. Human Validation Boost
            # ----------------------------------------------------------------
            is_human_validated = meta.get("human_validated", False)
            if isinstance(is_human_validated, str):
                is_human_validated = is_human_validated.lower() in ("true", "1")
            if is_human_validated:
                retrieval_score = round(retrieval_score + HUMAN_VALIDATION_BOOST, 4)

            precedent: dict = {
                "scenario_id": meta.get("scenario_id", doc_id),
                "summary": meta.get("summary") or document,
                "relevance": round(relevance, 4),
                "confidence_state": conf_state_str or (conf_state.value if conf_state else "unknown"),
                "original_confidence_state": meta.get("original_confidence_state", conf_state_str or "unknown"),
                "retrieval_weight": conf_weight,
                "retrieval_score": retrieval_score,
                "outcome_type": outcome_type_val,
                "winning_hypothesis": meta.get("winning_hypothesis", ""),
                "recommendation": meta.get("recommendation", ""),
                "timestamp": meta.get("timestamp", ""),
                "created_at": meta.get("created_at", meta.get("timestamp", "")),
                "evidence_ids": meta.get("evidence_ids", ""),
                "source_ids": sorted(candidate_sources),
                # ISSUE-002 Phase 3 — Human validation provenance
                "human_validated": bool(is_human_validated),
                "validated_at": meta.get("validated_at", ""),
                # Requirement 15.5 — stamp with RETRIEVAL
                "method": MethodTag.RETRIEVAL,
            }
            precedents.append(precedent)

        # Sort by retrieval_score descending (HIGH > MEDIUM > ABSTAIN > LOW for equivalent relevance)
        precedents.sort(key=lambda p: (p["retrieval_score"], p["relevance"]), reverse=True)

        if not precedents:
            logger.info(
                "retrieve_precedents: no precedents with relevance >= %.2f "
                "found for scenario=%s. Returning empty set.",
                self.RELEVANCE_THRESHOLD,
                scenario_id,
            )
        else:
            logger.info(
                "retrieve_precedents: returning %d precedent(s) for scenario=%s.",
                len(precedents),
                scenario_id,
            )

        return precedents[: self.MAX_RESULTS]


# ---------------------------------------------------------------------------
# Internal exception
# ---------------------------------------------------------------------------

class _DeadlineExceeded(Exception):
    """Raised internally when the store 5-second deadline is exceeded."""


# ---------------------------------------------------------------------------
# Module-level convenience functions
# ---------------------------------------------------------------------------


def store_precedent(
    result: InvestigationResult,
    chroma_client: Any,
    llm_provider: LLMProvider,
    db_conn: Any = None,  # reserved for future Postgres persistence; unused in MVP
    outcome_type: OutcomeType = OutcomeType.OBSERVED,
) -> bool:
    """
    Module-level convenience wrapper around MemoryEngine.store_precedent.

    Parameters
    ----------
    result        : Completed InvestigationResult to persist.
    chroma_client : chromadb.Client instance.
    llm_provider  : LLMProvider for embedding and summarization.
    db_conn       : Optional database connection (reserved; not used in MVP).
    outcome_type  : OutcomeType (OBSERVED or SIMULATED).

    Returns True on success, False after retries are exhausted (Req 15.2).

    Requirements: 15.1, 15.2
    """
    engine = MemoryEngine(chroma_client=chroma_client, llm_provider=llm_provider)
    return engine.store_precedent(result, outcome_type=outcome_type)


def retrieve_precedents(
    scenario_id: str,
    query_context: str,
    chroma_client: Any,
    llm_provider: LLMProvider,
    include_simulated: bool = False,
) -> list[dict]:
    """
    Module-level convenience wrapper around MemoryEngine.retrieve_precedents.

    Parameters
    ----------
    scenario_id   : ID of the scenario being investigated.
    query_context : Optional enriching context for the vector query.
    chroma_client : chromadb.Client instance.
    llm_provider  : LLMProvider for embedding.
    include_simulated : If True, includes SIMULATED outcomes (default False).

    Returns a list of precedent dicts sorted by retrieval_score descending.
    Returns [] with a log indication when no relevant precedents are found
    (Req 15.4).

    Requirements: 15.3, 15.4, 15.5
    """
    engine = MemoryEngine(chroma_client=chroma_client, llm_provider=llm_provider)
    return engine.retrieve_precedents(
        scenario_id,
        query_context,
        include_simulated=include_simulated,
    )
